baseURL = '/'
languageCode = 'en-us'
title = "Empty ship"

theme = "paper"

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  github = 'github.com/Roj'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  # home page profile
  #avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = ''
  bio = ''

  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTex math typesetting globally

[[menu.main]]
name = "[?]"
url = "/empty_ship"
weight = 1
